-- SYS_12 Phase 1A — register Bottom-2/3 Fade Multi Candidate Legs as an
-- audit-only H2H evaluator. Follows the SYS_8 seed pattern.
insert into public.pers_sys_systems_v2 (
  system_code,
  system_name,
  active,
  system_priority,
  system_group,
  primary_market,
  model_snapshot,
  execution_snapshot,
  allow_candidate,
  rounds_remaining_min,
  rounds_remaining_max,
  season_progress_round_min,
  date_start_mmdd,
  date_end_mmdd,
  clv_required,
  clv_min,
  staking_config,
  amplifier_config,
  overlay_config,
  weather_enabled,
  weather_active_decisioning_enabled
)
values (
  'SYS_12',
  'Bottom-2/3 Fade Multi Candidate Legs',
  true,
  12,
  'BOTTOM_FADE_MULTI',
  'H2H',
  'OPEN',
  'T30',
  true,
  null,
  null,
  null,
  null,
  null,
  false,
  null,
  '{
    "phase": "candidate_leg_only",
    "no_basket_construction": true,
    "market": "MATCH_RESULT",
    "leg_type": "H2H",
    "bottom_fade_teams": ["West Coast", "Richmond", "Essendon"],
    "tier2_teams": ["St Kilda", "Melbourne"],
    "tier3_excluded_teams": ["Gold Coast", "Port Adelaide", "North Melbourne", "GWS"]
  }'::jsonb,
  null,
  null,
  false,
  false
)
on conflict (system_code)
do update set
  system_name = excluded.system_name,
  active = excluded.active,
  system_priority = excluded.system_priority,
  system_group = excluded.system_group,
  primary_market = excluded.primary_market,
  model_snapshot = excluded.model_snapshot,
  execution_snapshot = excluded.execution_snapshot,
  allow_candidate = excluded.allow_candidate,
  rounds_remaining_min = excluded.rounds_remaining_min,
  rounds_remaining_max = excluded.rounds_remaining_max,
  season_progress_round_min = excluded.season_progress_round_min,
  date_start_mmdd = excluded.date_start_mmdd,
  date_end_mmdd = excluded.date_end_mmdd,
  clv_required = excluded.clv_required,
  clv_min = excluded.clv_min,
  staking_config = excluded.staking_config,
  amplifier_config = excluded.amplifier_config,
  overlay_config = excluded.overlay_config,
  weather_enabled = excluded.weather_enabled,
  weather_active_decisioning_enabled = excluded.weather_active_decisioning_enabled,
  updated_at = now();