// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzjaspfvhxxytjjfrsje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6amFzcGZ2aHh4eXRqamZyc2plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NDg3NjEsImV4cCI6MjA4ODUyNDc2MX0._SkqwP0gpFLkqDheraL9zsHiciQ8p42bgxkUyr6EH3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});